project:
  type: website
  output-dir: docs

website:
  site-url: https://amarbler.github.io
  title: "Alexander Marbler"
  search: true
  navbar:
    left:
      - text: Research
        href: index.qmd
      #- research/index.qmd
      #- projects/index.qmd
      #- data/index.qmd
      - text: Vita
        href: files/CV_Marbler.pdf
        target: _blank
      #- text: Blog
      #  href: index.qmd
      
  page-footer: 
    left: "[Alexander Marbler](http://amarbler.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 

format:
  html:
    theme:
      - cosmo
      - brand
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons/css/academicons.min.css">
      - text: |
          <!-- Google tag (gtag.js) -->
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-MM3WBEGQLF"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
          
            gtag('config', 'G-MM3WBEGQLF');
          </script>
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

