project:
  type: website
  output-dir: docs

website:
  site-url: amarbler.github.io
  title: "Alexander Marbler"
  navbar:
    left:
      - text: Research
        href: index.qmd
      #- research/index.qmd
      #- projects/index.qmd
      #- data/index.qmd
      - text: Vita
        href: https://github.com/amarbler/amarbler.github.io/blob/9a3ae93241103fd61b4b8b373161dbe7b29112f0/cv/CV_Marbler.pdf
      #- text: Blog
      #  href: index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

