project:
  type: website
  output-dir: docs

website:
  site-url: https://amarbler.github.io
  title: "Alexander Marbler"
  search: true
  navbar:
    background: light
    left:
      - text: Research
        href: index.qmd
      #- research/index.qmd
      #- projects/index.qmd
      #- data/index.qmd
      - text: Vita
        href: files/CV_Marbler.pdf
        target: _blank
      #- text: Blog
      #  href: index.qmd
      
  page-footer:
    left: "[Alexander Marbler](http://amarbler.github.io) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: ""
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      - cosmo
      - brand
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons/css/academicons.min.css">
      - text: |
          <script data-goatcounter="https://amarbler.goatcounter.com/count"
                  async src="//gc.zgo.at/count.js"></script>
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

